### ISSUE TITLE
Fatal-Error on Windows with phpcs 1.3.3. Referenced Sniffs not found

### ISSUE THREAD

**Issue by aw029** [typo3-ci/TYPO3CMS#20]
Hi,
I got an fatal-error while trying to execute phpcs with standard TYPO3CMS.
<code>
phpcs --standard=TYPO3CMS . 
</code>
<code>
Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff ../TYPO3SniffPool/Sniffs/Classes/LowercaseClassKeywordsSniff.php does
 not exist' in C:\xampp\php\pear\PHP\CodeSniffer.php:814
Stack trace:
#0 C:\xampp\php\pear\PHP\CodeSniffer.php(730): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement))
#1 C:\xampp\php\pear\PHP\CodeSniffer.php(623): PHP_CodeSniffer->getSniffFiles('C:\\xampp\\php\\pe...', 'TYPO3CMS')
#2 C:\xampp\php\pear\PHP\CodeSniffer.php(438): PHP_CodeSniffer->setTokenListeners('TYPO3CMS', Array)
#3 C:\xampp\php\pear\PHP\CodeSniffer\CLI.php(551): PHP_CodeSniffer->process(Array, 'TYPO3CMS', Array, false)
#4 C:\xampp\php\phpcs(37): PHP_CodeSniffer_CLI->process()
#5 {main}
  thrown in C:\xampp\php\pear\PHP\CodeSniffer.php on line 814
</code>

<code>
$ phpcs --version
PHP_CodeSniffer version 1.3.3 (stable) by Squiz Pty Ltd. (http://www.squiz.net)
</code>
<code>
$ phpcs -i
The installed coding standards are MySource, PEAR, PHPCS, Squiz, TYPO3CMS, TYPO3SniffPool and Zend
</code>

It seems to me, that he did not find any of the referenced rulesets from TYPO3CMS to TYPO3SniffPool.

Installation-Strategy was to clone both repositories into the "standards"-Directory of phpcs.

**Comment by Konafets** [comment]
If the bug still valid?

**Comment by aw029** [comment]
Hi, thanks for the reminder. I update to the latest PHPCS-Version. With version 1.5.5. there is no bug. I think, that Version 1.3.3. can not handle the referenced sniffs.
