### ISSUE TITLE
deny use clause in ext_localconf.php and ext_tables.php

### ISSUE THREAD

**Issue by kaystrobach** [typo3-ci/TYPO3CMS#21]
use clauses and namespaces can cause serious problems during extension execution.

**Comment by Konafets** [comment]
Hi Kay,

do you refer to a TYPO3CMS issue? This repository is related to theTYPO3  PHP_CodeSniffer standard.

**Comment by kaystrobach** [comment]
given you have an ext_localconf or ext_tables.php with the following content:

```
namespace some\name\space;

use TYPO3\CMS\...

GeneralUtility::mkDir(...);
```

And another ext_localconf looking like this:

```
namespace some\other\name\space;

use TYPO3\CMS\...

GeneralUtility::mkDir(...);
```

This will result in a file looking like:

```
namespace some\name\space;

use TYPO3\CMS\...

GeneralUtility::mkDir(...);

namespace some\other\name\space;

use TYPO3\CMS\...

GeneralUtility::mkDir(...);
```

Resulting in very strange errors during code execution, so i would recommend to deny use and namespace commands in that 2 files by CGL.
This is just caused because of the file merger

**Comment by Konafets** [comment]
Ok, please open an issue at https://forge.typo3.org/projects/typo3cms-doc-coding-guidelines/issues. We are not making the rules. It has to be discussed (at MailingList or Slack) and added to the CGL, after then  we create a check for it.
