### ISSUE TITLE
Bugfix the broken checks

### ISSUE THREAD

**Issue by evoWeb** [typo3-ci/TYPO3CMS#31]
Copyright notice must start with /*, but /** was found!
if i remove the extra *
Comment lines should be kept within a limit of about 80 characters but this comment has 301 characters!
Where the amout of character changes on every mouse position change over the comment.

Please change the rule to /** and all is fine.

One lined comments like
// Get the Category Tree
result in an error
Comment lines should be kept within a limit of about 80 characters but this comment has 316 characters!
This is amazing for such a small comment ;). Same do all other one line comments. The rule is pretty wrecked.

**Comment by andygrunwald** [comment]
Hey, thanks for your report.
Can you please post some further details like
* A code example which is wrong / marked as wrong
* A code example which is corrected / expected to be correct
* Version of PHP-CodeSniffer
* Version of TYPO3CMS CodeSniffs

That would help us a lot.
Real code (not an example) would be much more better (if possible).
Thank you.

**Comment by evoWeb** [comment]
PHP-CodeSniffer 2.3.2
TYPO3CMS latest Codesniff via global installation of composer just installed today

Examples i can only provide as screenshots:
http://www.evoweb.de/fileadmin/redaktion/examples/copyright_comment.png
http://www.evoweb.de/fileadmin/redaktion/examples/inline_comment.png
http://www.evoweb.de/fileadmin/redaktion/examples/star_tomany.png

**Comment by andygrunwald** [comment]
The TYPO3 copyright notice should be written as
```php
<?php
/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */
...
```
This is documented in the TYPO3 Coding Guidelines. See [Copyright notice](http://docs.typo3.org/typo3cms/CodingGuidelinesReference/PhpFileFormatting/FileStructure/Index.html#copyright-notice).
The TYPO3.CMS only implements those CGL.
If you want to change this from `/*` to `/**`, please add a pull request in the TYPO3-Documentations repository: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CodingGuidelines/blob/bf3c202a245adb5c5d79df7279be277c4d7c23ae/Documentation/PhpFileFormatting/FileStructure/Index.rst#copyright-notice

The other message `Comment lines should be kept within a limit of about 80 characters but this comment has 301 characters!` i can`t reproduce in my env.
I added a new unit test for this. See https://github.com/typo3-ci/TYPO3SniffPool/commit/dfa555823a7d1d264e60e285849a932fa9fba94b

* Which PHP version do you using?
* Which operating system?
* Can you please create a screenshot from your phpcs config in PHPStorm as well?

**Comment by evoWeb** [comment]
About the length:
OS: Ubuntu
PHP: 5.5.9-1ubuntu4.9

/home/sebastian/.composer/vendor/bin/phpcs
PHP_CodeSniffer version 2.3.2 (stable) by Squiz (http://www.squiz.net)

installed as dependency of
composer global require "typo3-ci/typo3cms=dev-master"

**Comment by andygrunwald** [comment]
After a chat with @evoWeb he sent me the original file.
With this i could reproduce this bug.
This bug is fixed in https://github.com/typo3-ci/TYPO3SniffPool/commit/747d0b2f66b357b874ce7ebfc2cd86b103e22a21

TravisCI loves this as well: https://travis-ci.org/typo3-ci/TYPO3SniffPool
Please use the latest development version with of TYPO3SniffPool.
