### ISSUE TITLE
[TASK] Handle type hints correctly

### ISSUE THREAD

**Issue by machwatt** [typo3-ci/TYPO3CMS#33]
The following code would cause a type hint error.

    /**
     * Set the file references
     *
     * @param \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\TYPO3\CMS\Extbase\Domain\Model\FileReference> $files The files
     *
     * @return void
     */
    public function setFiles($files) {
        $this->files = $files;
    }

```Type hint \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\TYPO3\CMS\Extbase\Domain\Model\FileReference> missing for $files (TYPO3SniffPool.Commenting.FunctionComment.TypeHintMissing)```

How would one fix this, as the type hint woluld break the code.

**Comment by Konafets** [comment]
Fixed in https://github.com/typo3-ci/TYPO3SniffPool/issues/75
